---
# tasks file for haproxy
- name: Fail on not Debian
  ansible.builtin.fail:
    msg: Playbook is not designed to run on non-Debian systems.
  when: ansible_facts['os_family']|lower != 'debian'

- name: Fail on ip_addr not defined
  ansible.builtin.fail:
    msg: haproxy_ip_addr is not defined
  when: haproxy_ip_addr is not defined

- name: Install haproxy for Debian
  ansible.builtin.apt:
    name: haproxy
    state: latest
    update_cache: true

- name: Starting and enabling service
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: true

- name: Allow all access to tcp port 80 (does not enable ufw)
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Ensure /etc/haproxy/haproxy.cfg exits
  ansible.builtin.file:
    path: /etc/haproxy/haproxy.cfg
    state: file

- name: Add lines to haproxy.cfg
  ansible.builtin.lineinfile:
    path: /etc/haproxy/haproxy.cfg
    line: "{{ item.line }}"
    create: false
  loop:
    - { line: "frontend www.example.com" }
    - { line: "    bind *:80" }
    - { line: "    default_backend web-servers" }
    - { line: "backend web-servers" }
    - { line: "    balance roundrobin"}
  notify: Restart haproxy

- name: Add server lines to haproxy.cfg
  ansible.builtin.lineinfile:
    path: /etc/haproxy/haproxy.cfg
    line: "    server web{{ idx }} {{ item }}:80"
    create: false
  loop: "{{ haproxy_ip_addr }}"
  loop_control:
    index_var: idx
  notify: Restart haproxy
