# https://docs.ansible.com/ansible/latest/collections/amazon/aws/docsite/guide_aws.html
- name: Set up AWS Infrastructure
  hosts: localhost
  gather_facts: false
  vars:
    vpc_cidr_block: 10.0.0.0/16
    subnet_a:
      az: us-east-1d
      cider_block: 10.0.1.0/24
    subnet_b:
      az: us-east-1a
      cider_block: 10.0.2.0/24
  tasks:
    - name: Create a VPC
      amazon.aws.ec2_vpc_net:
        name: ansible_vpc
        region: us-east-1
        state: present
        cidr_block: "{{ vpc_cidr_block }}"
        tags:
          Ansible_created: true
      register: vpc

    - name: Create subnet A
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ subnet_a.cider_block }}"
        az: "{{ subnet_a.az }}"

    - name: Create subnet B
      amazon.aws.ec2_vpc_subnet:
        state: present
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ subnet_b.cider_block }}"
        az: "{{ subnet_b.az }}"

    - name: Create security Group for Frontend
      amazon.aws.ec2_security_group:
        description: "Frontend security group"
        name: frontend-sg
        state: present
        vpc_id: "{{ vpc.vpc.id }}"
        rules:
          - proto: tcp
            ports:
              - 80
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port 80
          - proto: tcp
            ports:
              - 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all for ssh

    - name: Create security Group for Backend
      amazon.aws.ec2_security_group:
        description: "Backend security group"
        name: backend-sg
        state: present
        vpc_id: "{{ vpc.vpc.id }}"
        rules:
          - proto: tcp
            ports:
              - 3306
            cidr_ip: "{{ vpc_cidr_block }}"
            rule_desc: allow all on port 3306

    - name: Create EC2 instance ssh key
      amazon.aws.ec2_key:
        name: ansible_key
        key_type: ed25519
        file_name: ./secret/aws_ssh_key
        state: present

    # https://docs.ansible.com/ansible/latest/collections/amazon/aws/ec2_instance_module.html#ansible-collections-amazon-aws-ec2-instance-module
    # - name: Create EC2 instances
    #   amazon.aws.ec2_instance:

    # - name: Create RDS instance
